[build-system]
requires = [
    "hatchling==1.32.0",
    "hatch-vcs==0.5.0",
]
build-backend = "hatchling.build"

[project]
name = "praeco"
description = "praeco - Interfaces for publishing workflow recipes, instances and related assets"
readme = "docs/README.md"
keywords = [ "pyiron",]
requires-python = ">=3.11, <3.14"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "pandas==3.0.3",
    "pydantic==2.13.4",
    "rdflib==7.6.0",
    "requests==2.34.2",
    "sparqlwrapper==2.0.0",
]
dynamic = [ "version",]
authors = [
    { name = "Marian Bruns", email = "m.bruns@mpi-susmat.de" },
]

[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://pyiron.org/"
Documentation = "https://praeco.readthedocs.io"
Repository = "https://github.com/pyiron/praeco"

[tool.hatch.build]
include = [
    "praeco"
]

[tool.hatch.build.hooks.vcs]
version-file = "praeco/_version.py"

[tool.hatch.build.targets.sdist]
include = [
    "praeco"
]

[tool.hatch.build.targets.wheel]
packages = [
    "praeco"
]

[tool.hatch.version]
source = "vcs"
path = "praeco/_version.py"

[tool.ruff]
exclude = ["docs", "notebooks"]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["E501"] #ignore line-length violations

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # Ignore unused imports in init files -- we specify APIs this way

[tool.black]
extend-exclude = '''
(
  ^/docs
)
'''

[tool.mypy]
exclude = [
    "^docs/conf\\.py$",
    "^tests/",
]
ignore_missing_imports = true
strict_equality = true
non_interactive = true
install_types = true
